<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>"Глубокое обучение". Продвинутый поток</b></h3>

<h2 style="text-align: center;"><b>Домашнее задание 2. Библиотека Numpy и линейная алгебра.
</b></h2>

---

In [1]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [0]:
import numpy as np
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?


# ========
# Ваш код здесь
print(a.ndim, a.shape)

flist = [ [1, 3, 4, 5],[1, 3, 4, 5], [1, 3, 4, 5],[1, 3, 4, 5]]

print([flist[j][2]  for j in range(len(flist))] )

# ========
print(a)
print(b)

2 (100, 100)
[4, 4, 4, 4]
[[0.81444147 0.5771695  0.99938183 ... 0.92199147 0.18554125 0.53061109]
 [0.57524722 0.40290354 0.81341824 ... 0.66024247 0.85642688 0.75942655]
 [0.13981637 0.22169724 0.65459725 ... 0.18718818 0.23564331 0.99795304]
 ...
 [0.27739395 0.76040179 0.90613036 ... 0.12098131 0.02936325 0.07940973]
 [0.56535459 0.66485084 0.26542942 ... 0.78382669 0.64013563 0.3911131 ]
 [0.17579683 0.32602199 0.75620382 ... 0.02489133 0.48535457 0.33055937]]
[[0.84092963 0.58028767 0.46520166 ... 0.3613074  0.65325455 0.99298672]
 [0.22968741 0.40832616 0.52057294 ... 0.59877814 0.23056045 0.39534739]
 [0.23124157 0.62141914 0.59818211 ... 0.25415258 0.3992672  0.34489402]
 ...
 [0.84542295 0.42513768 0.43931212 ... 0.76317173 0.44653392 0.09083107]
 [0.22727724 0.35154837 0.85823244 ... 0.81852075 0.03194845 0.63178754]
 [0.40432991 0.97772962 0.99907375 ... 0.15185317 0.83842076 0.13550568]]


In [0]:
def mult(a, b):
#     lst = []
#     tmp = []
#     x = 0.0
#     for i in range(a.shape[0]):
#         for j in range(b.shape[1]):
#             for k in range(b.shape[0]):
#                 x += a[i][k]*b[k][j]
#             tmp.append(x)
#             x = 0.0
#         print(tmp)
#         lst.append(list(tmp))
#         tmp = []
#     print(lst)
    
    def vector_mult(av, bv):
      return sum([av[i]*bv[i] for i in range(a.shape[1])])
  
  
    prod_list = [[vector_mult(a[i, :], b[:, j]) for j in range(a.shape[1])] for i in range(a.shape[1])]

   
  
  
    return prod_list

In [0]:
def np_mult(a, b):
    
  
    return np.dot(a,b)

In [0]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 240 µs, sys: 4.94 ms, total: 5.18 ms
Wall time: 6.4 ms


In [0]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)


CPU times: user 339 ms, sys: 0 ns, total: 339 ms
Wall time: 349 ms


In [0]:
print(len(M1))

100


In [0]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.3571366253017914e-11

In [0]:
a = [[23, 32, 234], [23, 465, 56]]
print(len(a[0]))

3


In [0]:
import numpy as np

def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param first: list of "size" lists, each contains "size" floats
    """
    result = [[0 for j in range(second.shape[1])] for i in range(first.shape[0])]
    print(result)
    for i in range(first.shape[0]):
        for j in range(second.shape[1]):
            for k in range(second.shape[0]):
                result[i][j] += first[i][k]*second[k][j]
    return result

def numpy_mult(first, second):
    return np.dot(first, second)

In [0]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[1, 2], [3, 4]])
print(a)
print(b)
print(no_numpy_mult(a, b))

[[1 0]
 [0 1]]
[[1 2]
 [3 4]]
[[0, 0], [0, 0]]
[[1, 2], [3, 4]]


### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [3]:
import numpy as np

def no_numpy_scalar(v1, v2):
    return np.sum(v1[i]*v2[i] for i in range(len(v1)))

def numpy_scalar (v1, v2):
    return np.dot(v1, v2)
v1 = [0, 1, 2]
v2 = [3, 4, 5]
print(no_numpy_scalar(v1, v2))
print(numpy_scalar(v1, v2))

14
14


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


In [4]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.33018484 0.25571163 0.40346574] [0.80777312 0.20755242 0.97790298]


In [5]:
%time product_1 = no_numpy_scalar(a,b)
%time product_2 = numpy_scalar(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Wall time: 999 µs
Wall time: 0 ns


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [15]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    result = sum([x if x%2==0 else 0 for x in np.diagonal(a)])
    # result = np.sum(np.diag(a)[np.diag(a)%2==0])
    return result

In [16]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
print(a)
print(np.diagonal(a))
print([x if x%2==0 else 0 for x in np.diagonal(a)])
print(np_diag_2k(a))

[[4 8 4 5 3]
 [4 9 3 6 2]
 [9 5 1 3 4]
 [4 5 5 6 9]
 [8 9 2 6 3]]
[4 9 1 6 3]
[4, 0, 0, 6, 0]
10


In [0]:
np.sum(list(filter(lambda x: x % 2 == 0, np.diag(a))))

10

In [0]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 43 µs, sys: 11 µs, total: 54 µs
Wall time: 57.2 µs


16

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [23]:
import numpy as np

def cumsum(A):
    result = np.cumsum(A, 1)
    return result

In [25]:
X = np.array([[1, 2, 2], [3, 3, 1], [1, 5, 5], [2, 3, 3]])
print(X)
print(cumsum(X))

[[1 2 2]
 [3 3 1]
 [1 5 5]
 [2 3 3]]
[[ 1  3  5]
 [ 3  6  7]
 [ 1  6 11]
 [ 2  5  8]]


### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [73]:
import numpy as np

def encode(a):
    # elements, repetitions = np.unique(a, return_counts=True)
    indices = np.r_[np.flatnonzero(np.diff(a)), len(a) - 1]
    elements = a[indices]
    repetitions = np.r_[indices[0] + 1, np.diff(indices)]
    return elements, repetitions
  
encode(np.array([1, 2, 2, 3, 3, 1, 1, 1, 5, 5, 2, 3, 3]))

(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 3, 2, 1, 2], dtype=int64))

In [74]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = encode(X)

Wall time: 0 ns


### Задание 6

Задан двумерный массив $X$. Для каждой строчки массива $X$ необходимо сделать следующее преобразование.

Пусть дана строчка $x$. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (значение по умолчанию $a$=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив $x$ с преобразованным $x$ и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива $X$. Массив $X$ при этом должен остаться без изменений.


Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [110]:
import numpy as np
import copy


def transform(X, a=1):
    b = np.array(X[:, ::-1])
    b[:, 0::2] **= 3
    b[:, 1::2] = a
    X = np.concatenate((X, b), axis=1)
    return X

X = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(X)
print(transform(X, -1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[   1    2    3    4    5  125   -1   27   -1    1]
 [   6    7    8    9   10 1000   -1  512   -1  216]]
