<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>


---

## Домашнее задание 2: библиотека Numpy и линейная алгебра


Импортируем библиотеки:

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy import ndimage  # спецификатор для работы с изображениями
from scipy import misc
import scipy.stats as sps

from PIL import Image

%matplotlib inline

*Вопросы для самопроверки:*
1. Что такое NumPy?
2. Зачем используется и почему работает быстрее?
3. Что такое линейная алгебра?
4. Как она связана с машинным обучением и глубоким обучением?

### Задание 1

В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета numpy и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j), здесь i -- число строк,
# j -- число столбцов.
a = np.random.sample((10,10))
b = np.random.sample((10,10))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("a.ndim=", a.ndim, "b.ndim=", b.ndim)
print("a.shape=", a.shape, "b.shape=", b.shape)
print("len(a)=", len(a), "len(b)=", len(b))
# ========
#print(a)
#print(b)

a.ndim= 2 b.ndim= 2
a.shape= (10, 10) b.shape= (10, 10)
len(a)= 10 len(b)= 10


In [15]:
def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат
    c = np.zeros((a.shape[0], b.shape[1]))
    for i in range(a.shape[0]):
        for k in range(b.shape[1]):
            for j in range(a.shape[1]):
                c[i][k] += a[i][j] * b[j][k]
    return c
    pass

In [10]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return a.dot(b)
    pass

In [18]:
%%time
# засечем время работы функции без NumPy
mult(a,b)

Wall time: 2 ms


array([[3.00650224, 2.02467235, 2.57901775, 2.02100424, 2.8944833 ,
        2.27652537, 1.99179237, 2.54154479, 1.97003074, 1.49896171],
       [3.32822979, 2.85751249, 2.86610769, 2.71522667, 3.29981709,
        2.38880197, 2.69705718, 3.32958915, 2.55459937, 2.22442805],
       [2.68171565, 2.33999496, 2.36843042, 1.97320903, 2.70556482,
        2.22414842, 2.04829859, 2.87382519, 2.38285621, 2.02712857],
       [1.42675457, 1.58679432, 1.23720336, 1.07341769, 1.68447061,
        1.18592155, 0.84026131, 1.69358763, 1.50159454, 1.12987973],
       [4.3375583 , 3.90596733, 3.20448962, 3.66642963, 4.36261556,
        2.9473667 , 2.73775034, 4.42621378, 3.87519306, 3.05418952],
       [4.26064312, 3.59297375, 3.52227978, 3.67912748, 4.23695174,
        2.7658007 , 2.8799386 , 4.2408767 , 3.67677616, 3.14039319],
       [4.20110173, 3.38114572, 3.5316258 , 3.56169972, 4.35146824,
        2.88274614, 2.99785448, 4.15742904, 3.68267402, 3.00822687],
       [3.03822862, 2.9618888 , 2.5902977

In [22]:
mult(a,b) == np_mult(a,b)

array([[ True,  True,  True,  True,  True,  True, False,  True, False,
        False],
       [False, False,  True, False, False, False,  True,  True, False,
         True],
       [ True,  True,  True,  True, False,  True,  True, False,  True,
        False],
       [ True, False,  True,  True,  True,  True,  True, False,  True,
         True],
       [ True, False,  True, False,  True,  True,  True,  True,  True,
         True],
       [False, False, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True, False,  True,  True,  True,
        False],
       [ True,  True,  True,  True,  True,  True, False, False, False,
        False],
       [False, False,  True,  True,  True, False,  True,  True,  True,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [12]:
%%time
# засечем время работы функции с NumPy
np_mult(a,b)

Wall time: 0 ns


array([[3.00650224, 2.02467235, 2.57901775, 2.02100424, 2.8944833 ,
        2.27652537, 1.99179237, 2.54154479, 1.97003074, 1.49896171],
       [3.32822979, 2.85751249, 2.86610769, 2.71522667, 3.29981709,
        2.38880197, 2.69705718, 3.32958915, 2.55459937, 2.22442805],
       [2.68171565, 2.33999496, 2.36843042, 1.97320903, 2.70556482,
        2.22414842, 2.04829859, 2.87382519, 2.38285621, 2.02712857],
       [1.42675457, 1.58679432, 1.23720336, 1.07341769, 1.68447061,
        1.18592155, 0.84026131, 1.69358763, 1.50159454, 1.12987973],
       [4.3375583 , 3.90596733, 3.20448962, 3.66642963, 4.36261556,
        2.9473667 , 2.73775034, 4.42621378, 3.87519306, 3.05418952],
       [4.26064312, 3.59297375, 3.52227978, 3.67912748, 4.23695174,
        2.7658007 , 2.8799386 , 4.2408767 , 3.67677616, 3.14039319],
       [4.20110173, 3.38114572, 3.5316258 , 3.56169972, 4.35146824,
        2.88274614, 2.99785448, 4.15742904, 3.68267402, 3.00822687],
       [3.03822862, 2.9618888 , 2.5902977

### Задание 2

Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.
Аналогично -- с помощью библиотеки NumPy и без нее. Сравните скорость, объясните результат.

In [0]:
# функция, решающая задачу с помощью NumPy
def sec_av(A):
    # Ваш код здесь
    pass

In [0]:
# функция без NumPy
def stupid_sec_av(A):
    S = [0 for i in range(len(A))]
    for i in range(len(A)):
        # Ваш код здесь
    for i in range(len(A)):
        # Ваш код здесь
    return S

# зададим некоторую последовательность и проверим ее на ваших функциях. 
# Первая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10 ** 7) 

%time S1 = sec_av(A)
%time S2 = stupid_sec_av(A)
#проверим корректность:
np.abs(S1 - S2).sum()

### Задание 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все четные элементы исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться без изменений. В конце требуется слить массив $X$ с преобразованным $X$ и вывести в обратном порядке.

In [0]:
# функция, решающая задачу с помощью NumPy
def transformation(X, a=1):
    # Ваш код здесь
    return Y

In [0]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X):
    # Ваш код здесь
    return Y

In [0]:
X = sps.uniform.rvs(size=10 ** 7) 
# здесь код эффективнее примерно в 20 раз. 
# если Вы вдруг соберетесь печатать массив без np -- лучше сначала посмотрите на его размер
%time S1 = transformation(X)
%time S2 = stupid_transformation(X)
# проверим корректность:
np.abs(S1 - S2).sum()

Что вы можете сказать о скорости вычислений в `NumPy`? Ответ обоснуйте.

**Ответ:**

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [17]:
v1 = np.random.rand(3)
v2 = np.random.rand(3)
# print(v1, v1.shape, len(v1))
# print(v2, v2.shape, len(v2))
# print([v1[i] * v2[i] for i in range(len(v1))])
# sum([v1[i] * v2[i] for i in range(len(v1))])

In [18]:
def no_numpy_scalar(v1, v2):
    result = sum([v1[i] * v2[i] for i in range(len(v1))])
    return result

In [19]:
def numpy_scalar(v1, v2):
    result = np.matmul(v1, v2)
    return result

In [20]:
%time product_1 = no_numpy_scalar(v1,v2)
%time product_2 = numpy_scalar(v1,v2)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Wall time: 0 ns
Wall time: 0 ns


0.0

### Задание 5*

Нужно написать матричное произведение БЕЗ циклов и БЕЗ символа @, БЕЗ `np.dot` и вообще БЕЗ какой-либо вспомогательной функции из `numpy`, то есть пользуясь только индексированием, взятем суммы по нужным осям и поэлементным произведенем (да, это возможно). Рекомендуем гуглить по запросу "NumPy broadcasting"

In [0]:
def cool_matrix_product(A, B):
    # Ваш код здесь

In [0]:
# тут проверьте, что всё правильно перемножается

Ваш код не будет проверяться нами непосредственно, однако это очень и очень полезное упражнение.

## Бонусная часть (в тесте вопросов по ней не будет)

Image = 2-D численный массив
(или 3-D: CT, MRI, 2D + time; 4-D, …)
В текущем задании, image == Numpy array (np.array)

In [0]:
pic = misc.face()  # встроенная в библиотеку функция, которая загружает картинку с енотом

Выведите тип и размеры для переменной pic. Что лежит внутри?

In [0]:
print(#тут ваш код)

Если вы все сделали правильно, что для формы у вас выведется кортеж из трех чисел: (X, Y, 3). Предположите, откуда там 3?

**Ответ:**

С помощью функции ниже можно вывести изображение и посмотреть, что находится внутри:

In [0]:
plt.imshow(pic)

Убедитесь, что внутри массива `pic` действительно лежат числа. Выведите первые 10 записей.
Массив состоит из троек чисел, которые характеризуют глубину цвета для каждого пикселя. Из пикселей складывается картинка.

In [0]:
print(#тут ваш код)

Выведите значение максимального элемента в матрице. Выведите значение минимального. Выведите среднее по всем элементам матрице. В каких пределах лежат значения глубины цветов?

In [0]:
print(#тут ваш код)

### Задание 2

Теперь загрузим черно-белое изображение енота, чтобы наш массив был не 3-х мерным тензором, а двумерным массивом. Тензоры обрабатываются точно также, но для простоты пока что давайте работать с двумерными массивами, т.е. матрицами.

In [0]:
pic = misc.face(gray=True)

In [0]:
plt.imshow(#тут ваш код)

Выведите форму (shape) полученной картинки `pic`. Какие выводы можно сделать? Положите в `h`,`w` высоту и ширину картинки.

In [0]:
print(#тут ваш код)
h,w=#тут ваш код

Используя библиотеку `numpy`, отразите изображение по горизонтали. Выведите картинку.

Подсказка: не забывайте, что изображения -- это просто двумерные массивы

In [0]:
#тут ваш код

Теперь давайте повысим контрастность -- для этого к каждому пикселю прибавим 50 единиц

In [0]:
#тут ваш код

In [0]:
plt.imshow(pic)

Теперь давайте попробуем превратить наше одноканальное изображение в трехканальный (RGB) тензор. Для этого вместо каждого пикселя в одноканальном изображении (в двумерном массиве) поставим кортеж из трех элементов -- глубины красного, зеленого и голубого соотвественно. Восстановить по ч/б картинке цветной мы не можем, так как мы не можем взять утерянную информацию из ниоткуда, но можем усилить черные и белые участки. Для этого давайте заполним все три канала одинаковыми значениями, деленными на что-то очень большое. Например $--$ на $200$.  То есть, например, если в пикселе `pic[i][j]` лежало значение **200**, то для нового изображения `new_pic` мы заполняем `new_pic[i][j]` кортежем из трех чисел `int(pic[i][j]/3)`. Функция `int` $--$ округление до целой части.

In [0]:
new_pic = np.zeros((h,w,3)) #создадим пустую матрицу, куда будем записывать значения
for i in range(h):
    for j in range(w):
     #тут ваш код

In [0]:
plt.imshow(#тут ваш код)

### Задание 3

Теперь давайте уменьшим качество картинки в 16 раз, путем уменьшения качества изображения, т.е. теперь 16 пикселей по близости надо заполнить одним значением.

In [0]:
from sklearn.datasets import load_sample_image #импорт загрузчика изображения

In [0]:
china = load_sample_image('china.jpg')
plt.imshow(china)

Запишите в переменные `h`, `w`, `c` высоту, ширину, количество каналов соответственно для картинки `china`.

In [0]:
h, w, c = #тут ваш код

Теперь давайте непосредственно перейдем к изменению картинки $--$ мы предлагаем разбивать картинки на квадраты 4 на 4 и заполнять все 16 значений внутри квадрата левым верхним значением. Вы можете сделать иначе.

In [0]:
from copy import copy
compressed_pic = copy(china)
#тут ваш код     

Напишите функцию, которая считает несоотвествие между исходной и сжатой картинкой. Запустите ваш код для `compressed_pic`, `china`

In [0]:
def calculate_mismatch(a,b):
    mismatch=0
    #тут ваш код
    print(mismatch)

In [0]:
calculate_mismatch(#тут ваш код)

Посчитайте синус от каждого значения пикселей изображения `china` по всем каналам. Выведите картинку. Используйте функцию `np.sin` 

In [0]:
#тут ваш код

In [0]:
plt.imshow(#тут ваш код) 

Посмотрите на полученный результат. Как вы думаете, что можно делать с помощью такого преобразования? Какого рода объекты можно распознать?

### Задание 4*

Теперь давайте поработаем с аудиофайлами. Стандартный аудиофайл представляет собой обычный набор чисел, в котором хранятся значения частот, снятых с определенной периодичностью. Итак, самая простая аудиодорожка $-$ одномерный массив.

Первое, что нужно сделать $--$ установить библиотеку для работы с аудио. Она называется `librosa`. Гайд по установке: https://librosa.github.io/librosa/install.html


In [0]:
import librosa #импортируем библиотеку
import IPython.display

In [0]:
audio, sr= librosa.load('Test.wav')  
# записываем наш массив звуковых частот в файл аудио, sr -- число точек, записываемых в секунду. 
# чтобы файл открылся, он должен лежать в той же папке, что и файл HW_2.ipynb

Нашу дорожку можно воспроизвести в самом файле `.ipynb`:

In [0]:
IPython.display.Audio(audio, rate=sr)

Выведите тип данных переменной `audio`, найдите ее длительность и среднее.

In [0]:
print(#тут ваш код)

    Давайте посмотрим, как выглядит наша дорожка. Для этого используем библиотеку `matplotlib.pyplot`

In [0]:
plt.figure(figsize=(25,5))
plt.title('Test.wav')
plt.plot(audio)

Обрежьте последние 4 секунды файла

In [0]:
audio = #тут ваш код

Давайте уменьшим амплитуду на 25%. Что при этом изменится? Напоминаю, что вы всегда можете послушать изменения при помощи `IPython.display.Audio`

In [0]:
audio = #тут ваш код

А еще аудиодорожку можно ускорить. Для этого попробуйте потюнить параметр `rate`

In [0]:
IPython.display.Audio(audio, rate=sr)