<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>"Глубокое обучение". Продвинутый поток</b></h3>

<h2 style="text-align: center;"><b>Семинар 6. Основы библиотеки Pythorch </b></h2>


<h2 style="text-align: center;"><b>PyTorch basics: syntax, torch.cuda and torch.autograd</b></h2>

<p style="align: center;"><img src="https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png" width=400 height=100></p>

Hi! In this notebook we will cover the basics of the **PyTorch deep learning framework**. 

<h3 style="text-align: center;"><b>Intro</b></h3>

**Frameworks** are the specific code libraries with their own internal structure and pipelines.

There are many deep learning frameworks nowadays (02/2019). The difference between them is in the internal computation principles. For example, in **[Caffe](http://caffe.berkeleyvision.org/)** and **[Caffe2](https://caffe2.ai/)** you write the code using some "ready blocks" (just like the $LEGO^{TM}$ :). In **[TensorFlow](https://www.tensorflow.org/)** and **[Theano](http://deeplearning.net/software/theano/)** you declare the computation graph at first, then compile it and use it for inference/training (`tf.session()`). By the way, now TensorFlow (since v1.10) has the [Eager Execution](https://www.tensorflow.org/guide/eager), which can be handy for fast prototyping and debugging. **[Keras](https://keras.io/)** is a very popular and useful DL framework that allows to create networks fast and has many demanding features. 

<p style="align: center;"><img src="https://habrastorage.org/web/e3e/c3e/b78/e3ec3eb78d714a7993a6b922911c0866.png" width=500 height=500></p>  
<p style="text-align: center;"><i>Image credit: https://habr.com/post/334380/</i><p>

We will use PyTorch bacause it's been actively developed and supported by the community and [Facebook AI Research](https://research.fb.com/category/facebook-ai-research/).

<h3 style="text-align: center;"><b>Installation</b></h3>

The detailed instruction on how to install PyTorch you can find on the [official PyTorch website](https://pytorch.org/).

<h3 style="text-align: center;">Syntax<b></b></h3>

In [1]:
import torch

Some facts about PyTorch:  
- dynamic computation graph
- handy `torch.nn` and `torchvision` modules for fast neural network prototyping
- even faster than TensorFlow on some tasks
- allows to use GPU easily

If PyTorch was a formula, it would be:  

$$PyTorch = NumPy + CUDA + Autograd$$

(CUDA - [wiki](https://en.wikipedia.org/wiki/CUDA))

Let's see how we can use PyTorch to operate with vectors and tensors.  

Recall that **a tensor** is a multidimensional vector, e.g. :  

`x = np.array([1,2,3])` -- a vector = a tensor with 1 dimension (to be more precise: `(1,)`)  
`y = np.array([[1, 2, 3], [4, 5, 6]])` -- a matrix = a tensor with 2 dimensions (`(2, 3)` in this case)  
`z = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])` -- "a cube" (3, 3, 3) = a tensor with 3 dimensions (`(3, 3, 3)` in this case)

One real example of 3-dimensional tensor is **an image**, it has 3 dimensions: `height`, `width` and the `channel depth` (= 3 for color images, 1 for a greyscale). You can think of it as of parallelepiped consisting of the real numbers.

In PyTorch we will use `torch.Tensor` (`FloatTensor`, `IntTensor`, `ByteTensor`) for all the computations.

All tensor types:

In [0]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

We will use only `torch.FloatTensor()` and `torch.IntTensor()`. 

Let's begin to do something!

* Creating the tensor:

In [6]:
a = torch.FloatTensor([1, 2])
a

tensor([1., 2.])

In [7]:
a.shape

torch.Size([2])

In [8]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [11]:
b.shape
#b.shape[0]

torch.Size([2, 3])

In [18]:
# create tensor with specified shape (values are garbage)
x = torch.FloatTensor(2,3,4)

In [19]:
x

tensor([[[0.0000e+00, 5.9694e-39, 7.7052e+31, 7.2148e+22],
         [2.5226e-18, 1.6898e-04, 1.0072e-11, 1.2353e-08],
         [2.6260e-06, 4.0971e-11, 1.7061e-07, 2.9571e-18]],

        [[6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27],
         [6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22],
         [1.1970e+22, 1.6917e-04, 1.0301e-11, 6.8000e+22]]])

In [20]:
x = torch.FloatTensor(100)
x

tensor([7.2056e+22, 2.1720e+29, 1.8057e+28, 5.1412e+31, 7.5338e+28, 6.1687e+16,
        6.3370e-10, 5.2002e+22, 2.5038e-12, 1.6614e-04, 5.3193e+22, 2.6318e-12,
        1.0384e-05, 5.2598e+22, 2.5182e-12, 1.0141e-08, 5.4367e+22, 8.0252e+17,
        2.0190e-19, 1.3563e-19, 1.3563e-19, 6.4893e-07, 5.3775e+22, 2.6175e-12,
        2.5957e-06, 5.4373e+22, 2.5606e-12, 6.3371e-10, 5.2600e+22, 2.5181e-12,
        1.0139e-08, 5.2893e+22, 8.2951e+17, 2.0190e-19, 1.3563e-19, 1.3563e-19,
        2.5957e-06, 5.2009e+22, 2.5890e-12, 6.3375e-10, 5.2305e+22, 2.5181e-12,
        1.0383e-05, 5.2304e+22, 2.6033e-12, 1.6613e-04, 5.2305e+22, 8.2953e+17,
        1.7035e+28, 1.3589e-19, 1.3563e-19, 6.1678e+16, 4.2650e-08, 8.1428e-13,
        1.4586e-19, 6.8240e-07, 8.1425e-13, 1.4586e-19, 2.6656e-09, 8.1430e-13,
        1.4587e-19, 1.0430e-08, 8.1427e-13, 3.1437e-12, 1.3589e-19, 1.3563e-19,
        4.5071e+16, 1.6897e-04, 1.3028e-11, 1.4586e-19, 1.6594e-07, 8.1428e-13,
        1.4586e-19, 1.0918e-05, 8.1435e-

In [21]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

**Note:** if you create `torch.Tensor` with the following constructor it will be filled with the "random trash numbers":

In [22]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[6553710, 3342433, 7077980, 6422633],
         [7536732, 7602281, 2949221, 6357104]],

        [[7012451, 6750305, 7536741, 7602268],
         [7471215, 6815843, 6553692, 7536745]],

        [[7471220, 6422633, 7602293, 7274601],
         [7536750, 7798876, 6881381, 7667810]]], dtype=torch.int32)

Here is a way to fill a new tensor with zeroes:

In [23]:
x = torch.IntTensor(3, 2, 4).zero_()
x

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=torch.int32)

## Как писать на torch, если знаешь numpy

Все функции на numpy имеют соответствующие функции на torch. Их соответствие вы можете посмотреть здесь:

https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

`np.reshape()` == `torch.view()`:

In [24]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [25]:
b.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

**Note:** `torch.view()` creates a new tensor, one the old one remains unchanged

In [26]:
b.view(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [29]:
# the first dimension will be found automatically
b.view(-1, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

* Change a tensor type:

In [30]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [31]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [32]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

**Note:** `.type_as()` creates a new tensor, the old one remains unchanged

In [33]:
a

tensor([ 1.5000,  3.2000, -7.0000])

* Indexing is just like in `NumPy`:

In [34]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [36]:
a[0, 0]

tensor(100.)

In [37]:
a[0][0]

tensor(100.)

In [38]:
a[0:2, 0:2]

tensor([[100.,  20.],
        [ 15., 163.]])

## Exercise 1

1) create 2 float tensors: a(3, 4), b(12,) <br/>
2) create tensor c, that is the same as b but with shape (2, 2, 3) <br>
3) print first column of a using indexing

In [72]:
a = torch.FloatTensor(range(12)).view(3, 4)
b = torch.FloatTensor(range(12))

In [69]:
c = b.view(2, 2, 3)
c

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [75]:
a[0:, 0:1]
#a[:, 0]

tensor([[0.],
        [4.],
        [8.]])

**Ariphmetics and boolean operations** and their analogues:  

| Оператор | Аналог |
|:-:|:-:|
|`+`| `torch.add()` |
|`-`| `torch.sub()` |
|`*`| `torch.mul()` |
|`/`| `torch.div()` |

* Addition:

In [39]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [40]:
a + b

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [43]:
a.add(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [44]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [45]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

* Subtraction:

In [46]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [47]:
a.sub(b)

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

* Multiplication (elementwise):

In [48]:
a * b

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [-1.0000e+04, -4.0000e+04, -9.0000e+04]])

In [49]:
a.mul(b)

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [-1.0000e+04, -4.0000e+04, -9.0000e+04]])

* Division (elementwise):

In [50]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [51]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

Лучше:

In [52]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

**Note:** all this operations create new tensors, the old tensors remain unchanged

In [53]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [54]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

## Exercise 2

1) create 2 float tensors: `a` (5, 2), `b` (1, 10) <br/>
2) create tensor `c`, that is the same as `b` but with shape (5, 2) <br>
3) do arithmetics with `a` and `c`

In [77]:
a = torch.FloatTensor(range(10)).view(5, 2)
b = torch.FloatTensor(range(10)).view(1, 10)
c = b.view(5, 2)

In [82]:
a.mul(c)

tensor([[ 0.,  1.],
        [ 4.,  9.],
        [16., 25.],
        [36., 49.],
        [64., 81.]])

* Comparison operators:

In [55]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [56]:
a == b

tensor([[0, 0, 0],
        [0, 0, 0],
        [1, 1, 1]], dtype=torch.uint8)

In [57]:
a != b

tensor([[1, 1, 1],
        [1, 1, 1],
        [0, 0, 0]], dtype=torch.uint8)

In [58]:
a < b

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [59]:
a > b

tensor([[1, 1, 1],
        [1, 1, 1],
        [0, 0, 0]], dtype=torch.uint8)

* Using boolean mask indexing:

In [60]:
print(a)
a[a > b]

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])


tensor([ 1.,  2.,  3., 10., 20., 30.])

In [61]:
b[a == b]

tensor([100., 200., 300.])

Elementwise application of the **universal functions**:

In [83]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

In [84]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [85]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [86]:
a.cos()

tensor([[ 0.5403, -0.4161, -0.9900],
        [-0.8391,  0.4081,  0.1543],
        [ 0.8623,  0.4872, -0.0221]])

In [87]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [88]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [89]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [90]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

* The sum, mean, max, min:

In [91]:
a.sum()

tensor(666.)

In [92]:
a.mean()

tensor(74.)

Along axis:

In [93]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [94]:
a.sum(dim=0)

tensor([111., 222., 333.])

In [95]:
a.sum(1)

tensor([  6.,  60., 600.])

In [96]:
a.max()

tensor(300.)

In [98]:
a.max(1)

torch.return_types.max(
values=tensor([  3.,  30., 300.]),
indices=tensor([2, 2, 2]))

In [99]:
a.min()

tensor(1.)

In [100]:
a.min(0)

torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))

**Note:** the second tensor returned by `.max()` and `.min()` contains the indices of max/min elements along this axis. E.g. in that case `a.min()` returned `(1, 2, 3)` which are the minimum elements along 0 axis (along columns) and their indices along 0 axis are `(0, 0, 0)`.

## Exercise 3

Create tensor `a` (100, 780, 780, 3) (this could be interpreted as 100 photos of 780x780 size and 3 color channels) and print first element of that array as a picture (use matplotlib.pyplot). <br/>
Print mean of the elements by 1st axis (mean picture over all pictures) and by 4th axis (mean ov color channel for every picture).

In [102]:
a = torch.FloatTensor(100, 780, 780, 3)

In [105]:
pics_mean = a.mean(dim=0)
pics_mean.shape

torch.Size([780, 780, 3])

In [106]:
channels_mean = a.mean(dim=3)
channels_mean.shape

torch.Size([100, 780, 780])

**Matrix operations**:

* Transpose a tensor:

In [107]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [108]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

It is not not the inplace operation too:

In [109]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

* Dot product of vectors:

In [110]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [111]:
a.dot(b)

tensor(-141.)

In [112]:
a.shape, b.shape

(torch.Size([6]), torch.Size([6]))

In [113]:
azz @ b

NameError: name 'azz' is not defined

In [114]:
type(a)

torch.Tensor

In [115]:
type(b)

torch.Tensor

In [116]:
type(a @ b)

torch.Tensor

* Matrix product:

In [117]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [118]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [119]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

Remain unchanged:

In [120]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [121]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

In [122]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [123]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [124]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

If we unroll the tensor `b` in an array (`torch.view(-1)`) the multiplication would be like with the column:

In [125]:
b

tensor([[ -1.],
        [-10.],
        [100.]])

In [126]:
b.view(-1)

tensor([ -1., -10., 100.])

In [128]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [127]:
a @ b.view(-1)

tensor([  279.,  2790., 27900.])

In [129]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

**From NumPu to PyTorch conversion**:

In [130]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[0.92340097, 0.71748115, 0.44280475],
       [0.03279199, 0.54962697, 0.25887129],
       [0.91518268, 0.24579258, 0.41542153]])

In [131]:
b = torch.from_numpy(a)
b

tensor([[0.9234, 0.7175, 0.4428],
        [0.0328, 0.5496, 0.2589],
        [0.9152, 0.2458, 0.4154]], dtype=torch.float64)

**NOTE!** `a` and `b` have the same data storage, so the changes in one tensor will lead to the changes in another:

In [132]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [133]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**From PyTorch to NumPy conversion:**

In [134]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[2.5226e-18, 1.6898e-04, 1.0072e-11, 1.2353e-08],
         [4.1264e-08, 4.1881e-11, 4.2192e-08, 2.9575e-18],
         [6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27]],

        [[6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22],
         [1.1970e+22, 1.6917e-04, 1.0301e-11, 6.8000e+22],
         [8.2656e-10, 1.7565e-04, 6.3013e-10, 2.6950e-09]]])

In [135]:
type(a)

torch.Tensor

In [136]:
x = a.numpy()
x

array([[[2.5225907e-18, 1.6897990e-04, 1.0072204e-11, 1.2353028e-08],
        [4.1263949e-08, 4.1881366e-11, 4.2191662e-08, 2.9574786e-18],
        [6.7333120e+22, 1.7590538e+22, 1.7184218e+25, 4.3221663e+27]],

       [[6.1971537e-04, 7.2443192e+22, 1.7728345e+28, 7.0366722e+22],
        [1.1970246e+22, 1.6917058e-04, 1.0300692e-11, 6.7999756e+22],
        [8.2656265e-10, 1.7564515e-04, 6.3012895e-10, 2.6949589e-09]]],
      dtype=float32)

In [137]:
x.shape

(2, 3, 4)

In [138]:
type(x)

numpy.ndarray

Let's write the `forward_pass(X, w)` ($w_0$ is a part of the $w$) for a single neuron (activation = sigmoid) using PyTorch:

In [141]:
def forward_pass(X, w):
    return torch.sigmoid(X @ w)

In [142]:
X = torch.FloatTensor([[-5, 5], [2, 3], [1, -1]])
w = torch.FloatTensor([[-0.5], [2.5]])
result = forward_pass(X, w)
print('result: {}'.format(result))

result: tensor([[1.0000],
        [0.9985],
        [0.0474]])


<h3 style="text-align: center;"><a href="https://ru.wikipedia.org/wiki/CUDA">CUDA</a></h3>

[CUDA documentation](https://docs.nvidia.com/cuda/)

We can use both CPU (Central Processing Unit) and GPU (Graphical Processing Unit) to make the computations with PyTorch. We can switch between them easily, this is one of the most important things in PyTorch framework.

In [143]:
x = torch.FloatTensor(1024, 1024).uniform_()
x

tensor([[0.6764, 0.7330, 0.4400,  ..., 0.1052, 0.9731, 0.4554],
        [0.3554, 0.2025, 0.7941,  ..., 0.8469, 0.0212, 0.8435],
        [0.9659, 0.6654, 0.2714,  ..., 0.3324, 0.5882, 0.8457],
        ...,
        [0.0872, 0.9689, 0.6670,  ..., 0.7070, 0.1467, 0.4895],
        [0.0502, 0.1906, 0.4372,  ..., 0.8150, 0.1836, 0.0089],
        [0.4885, 0.7832, 0.5167,  ..., 0.8588, 0.8204, 0.4833]])

In [144]:
x.is_cuda

False

Place a tensor on GPU:

In [145]:
x = x.cuda()

AssertionError: Torch not compiled with CUDA enabled

In [146]:
x

tensor([[0.6764, 0.7330, 0.4400,  ..., 0.1052, 0.9731, 0.4554],
        [0.3554, 0.2025, 0.7941,  ..., 0.8469, 0.0212, 0.8435],
        [0.9659, 0.6654, 0.2714,  ..., 0.3324, 0.5882, 0.8457],
        ...,
        [0.0872, 0.9689, 0.6670,  ..., 0.7070, 0.1467, 0.4895],
        [0.0502, 0.1906, 0.4372,  ..., 0.8150, 0.1836, 0.0089],
        [0.4885, 0.7832, 0.5167,  ..., 0.8588, 0.8204, 0.4833]])

Let's multiply two tensors on GPU and then move the result on the CPU:

In [147]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

AssertionError: Torch not compiled with CUDA enabled

In [148]:
c

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [218]:
a

tensor([[0.4134, 0.7144, 0.3621,  ..., 0.8463, 0.9178, 0.3219],
        [0.2326, 0.5165, 0.3940,  ..., 0.9106, 0.6627, 0.2380],
        [0.4425, 0.2982, 0.3435,  ..., 0.5108, 0.7118, 0.4837],
        ...,
        [0.9319, 0.1526, 0.7414,  ..., 0.1972, 0.2364, 0.2674],
        [0.0087, 0.1227, 0.0506,  ..., 0.8916, 0.5391, 0.0966],
        [0.7177, 0.3744, 0.7303,  ..., 0.7601, 0.4462, 0.9392]])

Tensors placed on CPU and tensors placed on GPU are unavailable for each other:

In [0]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [220]:
a + b

RuntimeError: ignored

Example of working with GPU:

In [221]:
x = torch.FloatTensor(5, 5, 5).uniform_()

# check for CUDA availability (NVIDIA GPU)
if torch.cuda.is_available():
    # get the CUDA device name
    device = torch.device('cuda')          # CUDA-device object
    y = torch.ones_like(x, device=device)  # create a tensor on GPU
    x = x.to(device)                       # or just `.to("cuda")`
    z = x + y
    print(z)
    # you can set the type while `.to` operation
    print(z.to("cpu", torch.double))

tensor([[[1.6695, 1.9395, 1.4733, 1.6176, 1.3716],
         [1.5912, 1.1578, 1.6940, 1.1913, 1.8216],
         [1.1387, 1.8160, 1.3657, 1.7954, 1.7290],
         [1.0676, 1.2387, 1.0750, 1.7754, 1.3096],
         [1.7434, 1.9968, 1.6883, 1.6106, 1.6749]],

        [[1.6908, 1.8940, 1.6391, 1.4692, 1.5364],
         [1.8591, 1.3123, 1.2625, 1.4673, 1.4177],
         [1.7043, 1.5180, 1.1830, 1.9805, 1.8478],
         [1.7560, 1.4573, 1.3150, 1.2354, 1.0597],
         [1.7357, 1.5306, 1.2359, 1.3097, 1.2323]],

        [[1.6483, 1.3895, 1.4038, 1.2873, 1.4304],
         [1.6006, 1.1627, 1.2560, 1.9306, 1.7897],
         [1.3810, 1.8838, 1.7592, 1.5259, 1.3820],
         [1.6131, 1.5177, 1.4783, 1.0457, 1.9967],
         [1.6891, 1.1999, 1.8903, 1.5926, 1.3492]],

        [[1.3623, 1.2249, 1.4177, 1.2275, 1.3586],
         [1.7984, 1.5034, 1.5878, 1.0261, 1.1851],
         [1.2084, 1.1202, 1.6084, 1.6668, 1.5333],
         [1.4375, 1.9599, 1.8649, 1.8970, 1.3910],
         [1.9181, 1.5763,

<h3 style="text-align: center;">Autograd<b></b></h3>

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

Importing the `Variable()` class:

In [149]:
from torch.autograd import Variable

Now we will convert `torch.Tensor()` into `torch.Variable()` and we will get just the same tensor but the possibility to calculate the gradients with respect to this tensor.

If `а` is a tensor wrapped into `Variable()`, then `a.backward()` calculates the gradients with respect to all the tensors on which the tensor `a` depends.

**Note:** If you use `pytorch 0.4.0` version (or newer), then `torch.Tensor` and `torch.Variable()` were merged into `torch.Tensor`, so one doesn't need to use `Variable()` any more. (`torch.Variable()` is deprecated).

The examples:

In [150]:
from torch.autograd import Variable

In [151]:
dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 3, 3, 10

# Create random Tensors to hold input and outputs.
# Setting requires_grad=False indicates that we do not need to compute gradients
# with respect to these Tensors during the backward pass.
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# Create random Tensors for weights.
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

# x = torch.FloatTensor(3, 1).uniform_()
# y = torch.FloatTensor(3, 1).uniform_()
# w = torch.FloatTensor(3, 3).uniform_() 
# b = torch.FloatTensor(3, 1).uniform_()

# x = Variable(x, requires_grad=True)
# y = Variable(x, requires_grad=False)
# w = Variable(w, requires_grad=True)
# b = Variable(b, requires_grad=True)

y_pred = (x @ w1).clamp(min=0).mm(w2)

loss = (y_pred - y).pow(2).sum()
# calculate the gradients
loss.backward()

In [152]:
print( Variable((y_pred - y).pow(2).sum()) )

tensor(9254.7539)


In [153]:
loss.grad

In [154]:
w1.grad

tensor([[ 925.8430, -715.0887,  206.2299],
        [4625.8887, 2422.7463,  -64.6453],
        [2028.0885,   50.7381,  -83.8440]])

In [155]:
b.grad

In [156]:
y.grad

In [157]:
loss.grad

**NOTE:** the gradients are placed into the `.grad` field of tensors (variables) on which gradients were calculated. Gradients *are not placed* in the variable `loss` here!

Here is how to get `torch.Tensor()` from the `Variable()` (`.data` field):

In [158]:
x

tensor([[ 2.6161, -1.1276,  0.1437],
        [ 1.4647, -0.9272,  0.7040],
        [-0.9664,  1.7427,  0.9931],
        [-0.3304,  1.4716,  0.4710],
        [ 0.8365,  0.6276,  1.3592],
        [ 0.6006,  1.6157, -1.0416],
        [-0.2507, -1.3446,  0.2688],
        [-0.7753, -0.6941,  0.3525],
        [ 1.0023, -0.4212, -0.6244],
        [ 0.4109,  2.3053,  0.5356],
        [-0.5320,  0.2670, -1.0922],
        [ 1.4956, -2.9413,  1.7375],
        [ 0.3156,  0.1543, -0.0908],
        [ 2.0881,  0.8399,  0.5710],
        [ 2.5749, -1.1084, -0.0941],
        [-2.2383,  2.4053,  0.0514],
        [-0.8988,  2.0671,  0.3352],
        [ 0.0438,  0.5800, -0.4143],
        [-0.4456,  0.2334, -0.3863],
        [-0.4694, -1.0978, -0.0068],
        [-0.4735,  0.9107,  0.9864],
        [ 1.0688,  0.0765,  1.5109],
        [-0.4808,  0.4545,  0.2258],
        [-1.1842,  1.2845,  0.0327],
        [ 0.8949,  0.0933,  1.8347],
        [-1.7118, -0.1355, -1.2798],
        [ 1.6152,  1.2709,  2.0281],
 

In [159]:
x.data

tensor([[ 2.6161, -1.1276,  0.1437],
        [ 1.4647, -0.9272,  0.7040],
        [-0.9664,  1.7427,  0.9931],
        [-0.3304,  1.4716,  0.4710],
        [ 0.8365,  0.6276,  1.3592],
        [ 0.6006,  1.6157, -1.0416],
        [-0.2507, -1.3446,  0.2688],
        [-0.7753, -0.6941,  0.3525],
        [ 1.0023, -0.4212, -0.6244],
        [ 0.4109,  2.3053,  0.5356],
        [-0.5320,  0.2670, -1.0922],
        [ 1.4956, -2.9413,  1.7375],
        [ 0.3156,  0.1543, -0.0908],
        [ 2.0881,  0.8399,  0.5710],
        [ 2.5749, -1.1084, -0.0941],
        [-2.2383,  2.4053,  0.0514],
        [-0.8988,  2.0671,  0.3352],
        [ 0.0438,  0.5800, -0.4143],
        [-0.4456,  0.2334, -0.3863],
        [-0.4694, -1.0978, -0.0068],
        [-0.4735,  0.9107,  0.9864],
        [ 1.0688,  0.0765,  1.5109],
        [-0.4808,  0.4545,  0.2258],
        [-1.1842,  1.2845,  0.0327],
        [ 0.8949,  0.0933,  1.8347],
        [-1.7118, -0.1355, -1.2798],
        [ 1.6152,  1.2709,  2.0281],
 

<h3 style="text-align: center;">Further reading:<b></b></h3>

*1). Official PyTorch tutorials: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py*

*2). arXiv article about the deep learning frameworks comparison: https://arxiv.org/pdf/1511.06435.pdf*

*3). Useful repo with different tutorials: https://github.com/yunjey/pytorch-tutorial*

*4). Facebook AI Research (main contributor of PyTorch) website: https://facebook.ai/developers/tools*